module.exports = {
  characterDetails: [
    {
      character_name: "Naruto Uzumaki",
      anime_name: "Naruto",
      hair_color: "Blonde",
      power_type: "Chakra",
      weapon_type: "Kunai, Shuriken",
      role: "Protagonist",
    },
    {
      character_name: "Sasuke Uchiha",
      anime_name: "Naruto",
      hair_color: "Black",
      power_type: "Chakra",
      weapon_type: "Kunai, Shuriken",
      role: "Deuteragonist",
    },
    {
      character_name: "Goku",
      anime_name: "Dragon Ball Z",
      hair_color: "Black",
      power_type: "Ki",
      weapon_type: "Power Pole",
      role: "Protagonist",
    },
    {
      character_name: "Vegeta",
      anime_name: "Dragon Ball Z",
      hair_color: "Black",
      power_type: "Ki",
      weapon_type: "Fist",
      role: "Supporting",
    },
    {
      character_name: "Luffy",
      anime_name: "One Piece",
      hair_color: "Black",
      power_type: "Devil Fruit",
      weapon_type: "Fist",
      role: "Protagonist",
    },
    {
      character_name: "Zoro",
      anime_name: "One Piece",
      hair_color: "Green",
      power_type: "Swordsmanship",
      weapon_type: "Katana",
      role: "Supporting",
    },
    {
      character_name: "Light Yagami",
      anime_name: "Death Note",
      hair_color: "Brown",
      power_type: "Intelligence",
      weapon_type: "Death Note",
      role: "Protagonist",
    },
    {
      character_name: "Eren Yeager",
      anime_name: "Attack on Titan",
      hair_color: "Brown",
      power_type: "Titan Shifter",
      weapon_type: "Omni-Directional Mobility Gear",
      role: "Protagonist",
    },
    {
      character_name: "Levi Ackerman",
      anime_name: "Attack on Titan",
      hair_color: "Black",
      power_type: "Combat Skills",
      weapon_type: "Omni-Directional Mobility Gear",
      role: "Supporting",
    },
    {
      character_name: "Edward Elric",
      anime_name: "Fullmetal Alchemist",
      hair_color: "Blonde",
      power_type: "Alchemy",
      weapon_type: "Automail",
      role: "Protagonist",
    },
    {
      character_name: "Alphonse Elric",
      anime_name: "Fullmetal Alchemist",
      hair_color: "Blonde",
      power_type: "Alchemy",
      weapon_type: "Fist",
      role: "Supporting",
    },
    {
      character_name: "Ichigo Kurosaki",
      anime_name: "Bleach",
      hair_color: "Orange",
      power_type: "Soul Reaper",
      weapon_type: "Zanpakuto",
      role: "Protagonist",
    },
    {
      character_name: "Rukia Kuchiki",
      anime_name: "Bleach",
      hair_color: "Black",
      power_type: "Soul Reaper",
      weapon_type: "Zanpakuto",
      role: "Supporting",
    },
    {
      character_name: "Natsu Dragneel",
      anime_name: "Fairy Tail",
      hair_color: "Pink",
      power_type: "Dragon Slayer Magic",
      weapon_type: "Fist",
      role: "Protagonist",
    },
    {
      character_name: "Erza Scarlet",
      anime_name: "Fairy Tail",
      hair_color: "Red",
      power_type: "Requip Magic",
      weapon_type: "Swords",
      role: "Supporting",
    },
    {
      character_name: "Killua Zoldyck",
      anime_name: "Hunter x Hunter",
      hair_color: "White",
      power_type: "Nen",
      weapon_type: "Claws",
      role: "Supporting",
    },
    {
      character_name: "Gon Freecss",
      anime_name: "Hunter x Hunter",
      hair_color: "Green",
      power_type: "Nen",
      weapon_type: "Fishing Rod",
      role: "Protagonist",
    },
    {
      character_name: "Saitama",
      anime_name: "One Punch Man",
      hair_color: "None",
      power_type: "Super Strength",
      weapon_type: "Fist",
      role: "Protagonist",
    },
    {
      character_name: "Genos",
      anime_name: "One Punch Man",
      hair_color: "Blonde",
      power_type: "Cyborg Enhancements",
      weapon_type: "Arm Cannons",
      role: "Supporting",
    },
    {
      character_name: "Kenshin Himura",
      anime_name: "Rurouni Kenshin",
      hair_color: "Red",
      power_type: "Swordsmanship",
      weapon_type: "Sakabato",
      role: "Protagonist",
    },
    {
      character_name: "Shoto Todoroki",
      anime_name: "My Hero Academia",
      hair_color: "Red and White",
      power_type: "Quirk (Half-Cold Half-Hot)",
      weapon_type: "Fist",
      role: "Supporting",
    },
    {
      character_name: "Izuku Midoriya",
      anime_name: "My Hero Academia",
      hair_color: "Green",
      power_type: "Quirk (One For All)",
      weapon_type: "Fist",
      role: "Protagonist",
    },
    {
      character_name: "Kakashi Hatake",
      anime_name: "Naruto",
      hair_color: "Silver",
      power_type: "Chakra",
      weapon_type: "Kunai, Shuriken",
      role: "Mentor",
    },
    {
      character_name: "Itachi Uchiha",
      anime_name: "Naruto",
      hair_color: "Black",
      power_type: "Chakra",
      weapon_type: "Kunai, Shuriken",
      role: "Antagonist",
    },
    {
      character_name: "Ryuk",
      anime_name: "Death Note",
      hair_color: "None",
      power_type: "Shinigami",
      weapon_type: "Death Note",
      role: "Supporting",
    },
    {
      character_name: "Mikasa Ackerman",
      anime_name: "Attack on Titan",
      hair_color: "Black",
      power_type: "Combat Skills",
      weapon_type: "Omni-Directional Mobility Gear",
      role: "Supporting",
    },
    {
      character_name: "Roy Mustang",
      anime_name: "Fullmetal Alchemist",
      hair_color: "Black",
      power_type: "Alchemy",
      weapon_type: "Gloves",
      role: "Supporting",
    },
    {
      character_name: "Winry Rockbell",
      anime_name: "Fullmetal Alchemist",
      hair_color: "Blonde",
      power_type: "Engineering",
      weapon_type: "Wrench",
      role: "Supporting",
    },
    {
      character_name: "Yoruichi Shihouin",
      anime_name: "Bleach",
      hair_color: "Purple",
      power_type: "Soul Reaper",
      weapon_type: "Fist",
      role: "Supporting",
    },
    {
      character_name: "Gray Fullbuster",
      anime_name: "Fairy Tail",
      hair_color: "Black",
      power_type: "Ice-Make Magic",
      weapon_type: "Fist",
      role: "Supporting",
    },
    {
      character_name: "Hisoka Morow",
      anime_name: "Hunter x Hunter",
      hair_color: "Red",
      power_type: "Nen",
      weapon_type: "Playing Cards",
      role: "Antagonist",
    },
    {
      character_name: "All Might",
      anime_name: "My Hero Academia",
      hair_color: "Blonde",
      power_type: "Quirk (One For All)",
      weapon_type: "Fist",
      role: "Mentor",
    },
    {
      character_name: "Kamina",
      anime_name: "Gurren Lagann",
      hair_color: "Blue",
      power_type: "Spiral Energy",
      weapon_type: "Sword",
      role: "Supporting",
    },
    {
      character_name: "Simon",
      anime_name: "Gurren Lagann",
      hair_color: "Black",
      power_type: "Spiral Energy",
      weapon_type: "Drill",
      role: "Protagonist",
    },
    {
      character_name: "Spike Spiegel",
      anime_name: "Cowboy Bebop",
      hair_color: "Brown",
      power_type: "Combat Skills",
      weapon_type: "Pistol",
      role: "Protagonist",
    },
    {
      character_name: "Faye Valentine",
      anime_name: "Cowboy Bebop",
      hair_color: "Brown",
      power_type: "Combat Skills",
      weapon_type: "Pistol",
      role: "Supporting",
    },
    {
      character_name: "Vash the Stampede",
      anime_name: "Trigun",
      hair_color: "Blonde",
      power_type: "Superhuman Abilities",
      weapon_type: "Pistol",
      role: "Protagonist",
    },
    {
      character_name: "Maka Albarn",
      anime_name: "Soul Eater",
      hair_color: "Blonde",
      power_type: "Soul Resonance",
      weapon_type: "Scythe",
      role: "Protagonist",
    },
    {
      character_name: "Soul Evans",
      anime_name: "Soul Eater",
      hair_color: "White",
      power_type: "Soul Resonance",
      weapon_type: "Scythe",
      role: "Supporting",
    },
    {
      character_name: "Kirito",
      anime_name: "Sword Art Online",
      hair_color: "Black",
      power_type: "Swordsmanship",
      weapon_type: "Sword",
      role: "Protagonist",
    },
    {
      character_name: "Asuna Yuuki",
      anime_name: "Sword Art Online",
      hair_color: "Chestnut",
      power_type: "Swordsmanship",
      weapon_type: "Rapier",
      role: "Supporting",
    },
    {
      character_name: "Lelouch Lamperouge",
      anime_name: "Code Geass",
      hair_color: "Black",
      power_type: "Geass",
      weapon_type: "Strategy",
      role: "Protagonist",
    },
    {
      character_name: "C.C.",
      anime_name: "Code Geass",
      hair_color: "Green",
      power_type: "Immortality",
      weapon_type: "Geass",
      role: "Supporting",
    },
    {
      character_name: "Touka Kirishima",
      anime_name: "Tokyo Ghoul",
      hair_color: "Blue",
      power_type: "Ghoul Abilities",
      weapon_type: "Kagune",
      role: "Supporting",
    },
    {
      character_name: "Rin Okumura",
      anime_name: "Blue Exorcist",
      hair_color: "Black",
      power_type: "Demon Powers",
      weapon_type: "Sword",
      role: "Protagonist",
    },
    {
      character_name: "Yukio Okumura",
      anime_name: "Blue Exorcist",
      hair_color: "Brown",
      power_type: "Exorcist Skills",
      weapon_type: "Guns",
      role: "Supporting",
    },
    {
      character_name: "Meliodas",
      anime_name: "Seven Deadly Sins",
      hair_color: "Blonde",
      power_type: "Demon Power",
      weapon_type: "Sword",
      role: "Protagonist",
    },
    {
      character_name: "Ban",
      anime_name: "Seven Deadly Sins",
      hair_color: "White",
      power_type: "Immortality",
      weapon_type: "Sacred Treasure",
      role: "Supporting",
    },
    {
      character_name: "Astro",
      anime_name: "Astro Boy",
      hair_color: "Black",
      power_type: "Robotic Abilities",
      weapon_type: "Arm Cannon",
      role: "Protagonist",
    },
    {
      character_name: "Black Jack",
      anime_name: "Black Jack",
      hair_color: "Black",
      power_type: "Medical Skills",
      weapon_type: "Scalpel",
      role: "Protagonist",
    },
    {
      character_name: "Doraemon",
      anime_name: "Doraemon",
      hair_color: "Blue",
      power_type: "Gadgets",
      weapon_type: "None",
      role: "Protagonist",
    },
    {
      character_name: "Nobita Nobi",
      anime_name: "Doraemon",
      hair_color: "Brown",
      power_type: "None",
      weapon_type: "None",
      role: "Supporting",
    },
    {
      character_name: "Sailor Moon",
      anime_name: "Sailor Moon",
      hair_color: "Blonde",
      power_type: "Magical Girl",
      weapon_type: "Moon Stick",
      role: "Protagonist",
    },
    {
      character_name: "Tuxedo Mask",
      anime_name: "Sailor Moon",
      hair_color: "Black",
      power_type: "Magical Abilities",
      weapon_type: "Rose",
      role: "Supporting",
    },
    {
      character_name: "Inuyasha",
      anime_name: "Inuyasha",
      hair_color: "Silver",
      power_type: "Demon Powers",
      weapon_type: "Tessaiga",
      role: "Protagonist",
    },
    {
      character_name: "Kagome Higurashi",
      anime_name: "Inuyasha",
      hair_color: "Black",
      power_type: "Spiritual Powers",
      weapon_type: "Bow and Arrow",
      role: "Supporting",
    },
    {
      character_name: "Guts",
      anime_name: "Berserk",
      hair_color: "Black",
      power_type: "Combat Skills",
      weapon_type: "Dragonslayer Sword",
      role: "Protagonist",
    },
    {
      character_name: "Griffith",
      anime_name: "Berserk",
      hair_color: "White",
      power_type: "Demonic Powers",
      weapon_type: "Sword",
      role: "Antagonist",
    },
    {
      character_name: "Alucard",
      anime_name: "Hellsing",
      hair_color: "Black",
      power_type: "Vampire",
      weapon_type: "Pistol",
      role: "Protagonist",
    },
    {
      character_name: "Seras Victoria",
      anime_name: "Hellsing",
      hair_color: "Blonde",
      power_type: "Vampire",
      weapon_type: "Harkonnen",
      role: "Supporting",
    },
    {
      character_name: "Kenshiro",
      anime_name: "Fist of the North Star",
      hair_color: "Black",
      power_type: "Hokuto Shinken",
      weapon_type: "Fist",
      role: "Protagonist",
    },
    {
      character_name: "Raoh",
      anime_name: "Fist of the North Star",
      hair_color: "Black",
      power_type: "Hokuto Shinken",
      weapon_type: "Fist",
      role: "Antagonist",
    },
    {
      character_name: "Soma Yukihira",
      anime_name: "Food Wars",
      hair_color: "Red",
      power_type: "Culinary Skills",
      weapon_type: "Knife",
      role: "Protagonist",
    },
    {
      character_name: "Erina Nakiri",
      anime_name: "Food Wars",
      hair_color: "Blonde",
      power_type: "Culinary Skills",
      weapon_type: "Knife",
      role: "Supporting",
    },
    {
      character_name: "Tanjiro Kamado",
      anime_name: "Demon Slayer",
      hair_color: "Black",
      power_type: "Breathing Techniques",
      weapon_type: "Nichirin Sword",
      role: "Protagonist",
    },
    {
      character_name: "Nezuko Kamado",
      anime_name: "Demon Slayer",
      hair_color: "Black",
      power_type: "Demon Powers",
      weapon_type: "Fist",
      role: "Supporting",
    },
    {
      character_name: "Zenitsu Agatsuma",
      anime_name: "Demon Slayer",
      hair_color: "Blonde",
      power_type: "Breathing Techniques",
      weapon_type: "Nichirin Sword",
      role: "Supporting",
    },
    {
      character_name: "Inosuke Hashibira",
      anime_name: "Demon Slayer",
      hair_color: "Black",
      power_type: "Breathing Techniques",
      weapon_type: "Dual Nichirin Swords",
      role: "Supporting",
    },
    {
      character_name: "Kamina",
      anime_name: "Gurren Lagann",
      hair_color: "Blue",
      power_type: "Spiral Energy",
      weapon_type: "Sword",
      role: "Supporting",
    },
    {
      character_name: "Simon",
      anime_name: "Gurren Lagann",
      hair_color: "Black",
      power_type: "Spiral Energy",
      weapon_type: "Drill",
      role: "Protagonist",
    },
    {
      character_name: "Spike Spiegel",
      anime_name: "Cowboy Bebop",
      hair_color: "Brown",
      power_type: "Combat Skills",
      weapon_type: "Pistol",
      role: "Protagonist",
    },
    {
      character_name: "Faye Valentine",
      anime_name: "Cowboy Bebop",
      hair_color: "Brown",
      power_type: "Combat Skills",
      weapon_type: "Pistol",
      role: "Supporting",
    },
    {
      character_name: "Vash the Stampede",
      anime_name: "Trigun",
      hair_color: "Blonde",
      power_type: "Superhuman Abilities",
      weapon_type: "Pistol",
      role: "Protagonist",
    },
    {
      character_name: "Maka Albarn",
      anime_name: "Soul Eater",
      hair_color: "Blonde",
      power_type: "Soul Resonance",
      weapon_type: "Scythe",
      role: "Protagonist",
    },
    {
      character_name: "Soul Evans",
      anime_name: "Soul Eater",
      hair_color: "White",
      power_type: "Soul Resonance",
      weapon_type: "Scythe",
      role: "Supporting",
    },
    {
      character_name: "Kirito",
      anime_name: "Sword Art Online",
      hair_color: "Black",
      power_type: "Swordsmanship",
      weapon_type: "Sword",
      role: "Protagonist",
    },
    {
      character_name: "Asuna Yuuki",
      anime_name: "Sword Art Online",
      hair_color: "Chestnut",
      power_type: "Swordsmanship",
      weapon_type: "Rapier",
      role: "Supporting",
    },
    {
      character_name: "Lelouch Lamperouge",
      anime_name: "Code Geass",
      hair_color: "Black",
      power_type: "Geass",
      weapon_type: "Strategy",
      role: "Protagonist",
    },
    {
      character_name: "C.C.",
      anime_name: "Code Geass",
      hair_color: "Green",
      power_type: "Immortality",
      weapon_type: "Geass",
      role: "Supporting",
    },
    {
      character_name: "Touka Kirishima",
      anime_name: "Tokyo Ghoul",
      hair_color: "Blue",
      power_type: "Ghoul Abilities",
      weapon_type: "Kagune",
      role: "Supporting",
    },
    {
      character_name: "Rin Okumura",
      anime_name: "Blue Exorcist",
      hair_color: "Black",
      power_type: "Demon Powers",
      weapon_type: "Sword",
      role: "Protagonist",
    },
    {
      character_name: "Yukio Okumura",
      anime_name: "Blue Exorcist",
      hair_color: "Brown",
      power_type: "Exorcist Skills",
      weapon_type: "Guns",
      role: "Supporting",
    },
    {
      character_name: "Meliodas",
      anime_name: "Seven Deadly Sins",
      hair_color: "Blonde",
      power_type: "Demon Power",
      weapon_type: "Sword",
      role: "Protagonist",
    },
    {
      character_name: "Ban",
      anime_name: "Seven Deadly Sins",
      hair_color: "White",
      power_type: "Immortality",
      weapon_type: "Sacred Treasure",
      role: "Supporting",
    },
    {
      character_name: "Astro",
      anime_name: "Astro Boy",
      hair_color: "Black",
      power_type: "Robotic Abilities",
      weapon_type: "Arm Cannon",
      role: "Protagonist",
    },
    {
      character_name: "Black Jack",
      anime_name: "Black Jack",
      hair_color: "Black",
      power_type: "Medical Skills",
      weapon_type: "Scalpel",
      role: "Protagonist",
    },
    {
      character_name: "Doraemon",
      anime_name: "Doraemon",
      hair_color: "Blue",
      power_type: "Gadgets",
      weapon_type: "None",
      role: "Protagonist",
    },
    {
      character_name: "Nobita Nobi",
      anime_name: "Doraemon",
      hair_color: "Brown",
      power_type: "None",
      weapon_type: "None",
      role: "Supporting",
    },
    {
      character_name: "Sailor Moon",
      anime_name: "Sailor Moon",
      hair_color: "Blonde",
      power_type: "Magical Girl",
      weapon_type: "Moon Stick",
      role: "Protagonist",
    },
    {
      character_name: "Tuxedo Mask",
      anime_name: "Sailor Moon",
      hair_color: "Black",
      power_type: "Magical Abilities",
      weapon_type: "Rose",
      role: "Supporting",
    },
    {
      character_name: "Inuyasha",
      anime_name: "Inuyasha",
      hair_color: "Silver",
      power_type: "Demon Powers",
      weapon_type: "Tessaiga",
      role: "Protagonist",
    },
    {
      character_name: "Kagome Higurashi",
      anime_name: "Inuyasha",
      hair_color: "Black",
      power_type: "Spiritual Powers",
      weapon_type: "Bow and Arrow",
      role: "Supporting",
    },
    {
      character_name: "Guts",
      anime_name: "Berserk",
      hair_color: "Black",
      power_type: "Combat Skills",
      weapon_type: "Dragonslayer Sword",
      role: "Protagonist",
    },
    {
      character_name: "Griffith",
      anime_name: "Berserk",
      hair_color: "White",
      power_type: "Demonic Powers",
      weapon_type: "Sword",
      role: "Antagonist",
    },
    {
      character_name: "Alucard",
      anime_name: "Hellsing",
      hair_color: "Black",
      power_type: "Vampire",
      weapon_type: "Pistol",
      role: "Protagonist",
    },
    {
      character_name: "Seras Victoria",
      anime_name: "Hellsing",
      hair_color: "Blonde",
      power_type: "Vampire",
      weapon_type: "Harkonnen",
      role: "Supporting",
    },
    {
      character_name: "Kenshiro",
      anime_name: "Fist of the North Star",
      hair_color: "Black",
      power_type: "Hokuto Shinken",
      weapon_type: "Fist",
      role: "Protagonist",
    },
    {
      character_name: "Raoh",
      anime_name: "Fist of the North Star",
      hair_color: "Black",
      power_type: "Hokuto Shinken",
      weapon_type: "Fist",
      role: "Antagonist",
    },
    {
      character_name: "Soma Yukihira",
      anime_name: "Food Wars",
      hair_color: "Red",
      power_type: "Culinary Skills",
      weapon_type: "Knife",
      role: "Protagonist",
    },
    {
      character_name: "Erina Nakiri",
      anime_name: "Food Wars",
      hair_color: "Blonde",
      power_type: "Culinary Skills",
      weapon_type: "Knife",
      role: "Supporting",
    },
    {
      character_name: "Tanjiro Kamado",
      anime_name: "Demon Slayer",
      hair_color: "Black",
      power_type: "Breathing Techniques",
      weapon_type: "Nichirin Sword",
      role: "Protagonist",
    },
    {
      character_name: "Nezuko Kamado",
      anime_name: "Demon Slayer",
      hair_color: "Black",
      power_type: "Demon Powers",
      weapon_type: "Fist",
      role: "Supporting",
    },
    {
      character_name: "Zenitsu Agatsuma",
      anime_name: "Demon Slayer",
      hair_color: "Blonde",
      power_type: "Breathing Techniques",
      weapon_type: "Nichirin Sword",
      role: "Supporting",
    },
    {
      character_name: "Inosuke Hashibira",
      anime_name: "Demon Slayer",
      hair_color: "Black",
      power_type: "Breathing Techniques",
      weapon_type: "Dual Nichirin Swords",
      role: "Supporting",
    },
    {
      character_name: "Gojo Satoru",
      anime_name: "Jujutsu Kaisen",
      hair_color: "White",
      power_type: "Cursed Technique",
      weapon_type: "Cursed Energy",
      role: "Mentor",
    },
    {
      character_name: "Yuji Itadori",
      anime_name: "Jujutsu Kaisen",
      hair_color: "Pink",
      power_type: "Cursed Energy",
      weapon_type: "Fist",
      role: "Protagonist",
    },
    {
      character_name: "Megumi Fushiguro",
      anime_name: "Jujutsu Kaisen",
      hair_color: "Black",
      power_type: "Cursed Technique",
      weapon_type: "Shikigami",
      role: "Supporting",
    },
    {
      character_name: "Nobara Kugisaki",
      anime_name: "Jujutsu Kaisen",
      hair_color: "Orange",
      power_type: "Cursed Technique",
      weapon_type: "Hammer and Nails",
      role: "Supporting",
    },
    {
      character_name: "Denji",
      anime_name: "Chainsaw Man",
      hair_color: "Blonde",
      power_type: "Devil Powers",
      weapon_type: "Chainsaws",
      role: "Protagonist",
    },
    {
      character_name: "Power",
      anime_name: "Chainsaw Man",
      hair_color: "Pink",
      power_type: "Devil Powers",
      weapon_type: "Blood manipulation",
      role: "Supporting",
    },
    {
      character_name: "Makima",
      anime_name: "Chainsaw Man",
      hair_color: "Orange",
      power_type: "Devil Powers",
      weapon_type: "Control",
      role: "Antagonist",
    },
    {
      character_name: "Violet Evergarden",
      anime_name: "Violet Evergarden",
      hair_color: "Blonde",
      power_type: "Mechanical Arms",
      weapon_type: "Typewriter",
      role: "Protagonist",
    },
    {
      character_name: "Anya Forger",
      anime_name: "Spy x Family",
      hair_color: "Pink",
      power_type: "Telepathy",
      weapon_type: "None",
      role: "Protagonist",
    },
    {
      character_name: "Loid Forger",
      anime_name: "Spy x Family",
      hair_color: "Blonde",
      power_type: "Espionage Skills",
      weapon_type: "Various",
      role: "Protagonist",
    },
    {
      character_name: "Yor Forger",
      anime_name: "Spy x Family",
      hair_color: "Black",
      power_type: "Assassin Skills",
      weapon_type: "Various",
      role: "Protagonist",
    },
    {
      character_name: "Marin Kitagawa",
      anime_name: "My Dress-Up Darling",
      hair_color: "Blonde",
      power_type: "None",
      weapon_type: "None",
      role: "Protagonist",
    },
    {
      character_name: "Bojji",
      anime_name: "Ranking of Kings",
      hair_color: "Blonde",
      power_type: "Physical Abilities",
      weapon_type: "Sword",
      role: "Protagonist",
    },
    {
      character_name: "Kage",
      anime_name: "Ranking of Kings",
      hair_color: "Black",
      power_type: "Shadow Abilities",
      weapon_type: "None",
      role: "Supporting",
    },
    {
      character_name: "Joe",
      anime_name: "Megalo Box",
      hair_color: "Black",
      power_type: "Boxing Skills",
      weapon_type: "Fist",
      role: "Protagonist",
    },
    {
      character_name: "Thorfinn",
      anime_name: "Vinland Saga",
      hair_color: "Blonde",
      power_type: "Combat Skills",
      weapon_type: "Dagger",
      role: "Protagonist",
    },
    {
      character_name: "Askeladd",
      anime_name: "Vinland Saga",
      hair_color: "Blonde",
      power_type: "Combat Skills",
      weapon_type: "Sword",
      role: "Antagonist",
    },
    {
      character_name: "Thors",
      anime_name: "Vinland Saga",
      hair_color: "Black",
      power_type: "Combat Skills",
      weapon_type: "Sword",
      role: "Supporting",
    },
    {
      character_name: "Mob",
      anime_name: "Mob Psycho 100",
      hair_color: "Black",
      power_type: "Psychic Powers",
      weapon_type: "None",
      role: "Protagonist",
    },
    {
      character_name: "Reigen Arataka",
      anime_name: "Mob Psycho 100",
      hair_color: "Brown",
      power_type: "None",
      weapon_type: "Salt",
      role: "Supporting",
    },
    {
      character_name: "Rengoku Kyojuro",
      anime_name: "Demon Slayer",
      hair_color: "Red and Yellow",
      power_type: "Breathing Techniques",
      weapon_type: "Nichirin Sword",
      role: "Supporting",
    },
    {
      character_name: "Giyu Tomioka",
      anime_name: "Demon Slayer",
      hair_color: "Black",
      power_type: "Breathing Techniques",
      weapon_type: "Nichirin Sword",
      role: "Supporting",
    },
    {
      character_name: "Shinobu Kocho",
      anime_name: "Demon Slayer",
      hair_color: "Black and Purple",
      power_type: "Breathing Techniques",
      weapon_type: "Nichirin Sword",
      role: "Supporting",
    },
    {
      character_name: "Muzan Kibutsuji",
      anime_name: "Demon Slayer",
      hair_color: "Black",
      power_type: "Demon Powers",
      weapon_type: "Blood Demon Art",
      role: "Antagonist",
    },
    {
      character_name: "Sukuna",
      anime_name: "Jujutsu Kaisen",
      hair_color: "Pink",
      power_type: "Cursed Technique",
      weapon_type: "Cursed Energy",
      role: "Antagonist",
    },
    {
      character_name: "Nanami Kento",
      anime_name: "Jujutsu Kaisen",
      hair_color: "Blonde",
      power_type: "Cursed Technique",
      weapon_type: "Cursed Energy",
      role: "Supporting",
    },
    {
      character_name: "Maki Zenin",
      anime_name: "Jujutsu Kaisen",
      hair_color: "Black",
      power_type: "Physical Enhancement",
      weapon_type: "Various Weapons",
      role: "Supporting",
    },
    {
      character_name: "Todo Aoi",
      anime_name: "Jujutsu Kaisen",
      hair_color: "Black",
      power_type: "Cursed Technique",
      weapon_type: "Cursed Energy",
      role: "Supporting",
    },
    {
      character_name: "Aki Hayakawa",
      anime_name: "Chainsaw Man",
      hair_color: "Black",
      power_type: "Devil Powers",
      weapon_type: "Fox Devil",
      role: "Supporting",
    },
    {
      character_name: "Himeno",
      anime_name: "Chainsaw Man",
      hair_color: "Black",
      power_type: "Devil Powers",
      weapon_type: "Ghost Devil",
      role: "Supporting",
    },
    {
      character_name: "Annie Leonhart",
      anime_name: "Attack on Titan",
      hair_color: "Blonde",
      power_type: "Titan Shifter",
      weapon_type: "Omni-Directional Mobility Gear",
      role: "Antagonist",
    },
    {
      character_name: "Reiner Braun",
      anime_name: "Attack on Titan",
      hair_color: "Blonde",
      power_type: "Titan Shifter",
      weapon_type: "Omni-Directional Mobility Gear",
      role: "Antagonist",
    },
    {
      character_name: "Historia Reiss",
      anime_name: "Attack on Titan",
      hair_color: "Blonde",
      power_type: "Royal Blood",
      weapon_type: "Omni-Directional Mobility Gear",
      role: "Supporting",
    },
    {
      character_name: "Zeke Yeager",
      anime_name: "Attack on Titan",
      hair_color: "Blonde",
      power_type: "Titan Shifter",
      weapon_type: "Rock Throwing",
      role: "Antagonist",
    },
    {
      character_name: "Hawks",
      anime_name: "My Hero Academia",
      hair_color: "Blonde",
      power_type: "Quirk (Fierce Wings)",
      weapon_type: "Feathers",
      role: "Supporting",
    },
    {
      character_name: "Endeavor",
      anime_name: "My Hero Academia",
      hair_color: "Red",
      power_type: "Quirk (Hellflame)",
      weapon_type: "Fire",
      role: "Supporting",
    },
    {
      character_name: "Tomura Shigaraki",
      anime_name: "My Hero Academia",
      hair_color: "Light Blue",
      power_type: "Quirk (Decay)",
      weapon_type: "Touch",
      role: "Antagonist",
    },
    {
      character_name: "Ochako Uraraka",
      anime_name: "My Hero Academia",
      hair_color: "Brown",
      power_type: "Quirk (Zero Gravity)",
      weapon_type: "Touch",
      role: "Supporting",
    },
    {
      character_name: "Katsuki Bakugo",
      anime_name: "My Hero Academia",
      hair_color: "Blonde",
      power_type: "Quirk (Explosion)",
      weapon_type: "Explosions",
      role: "Supporting",
    },
    {
      character_name: "Pain",
      anime_name: "Naruto",
      hair_color: "Orange",
      power_type: "Chakra",
      weapon_type: "Rinnegan",
      role: "Antagonist",
    },
    {
      character_name: "Madara Uchiha",
      anime_name: "Naruto",
      hair_color: "Black",
      power_type: "Chakra",
      weapon_type: "Sharingan",
      role: "Antagonist",
    },
    {
      character_name: "Hinata Hyuga",
      anime_name: "Naruto",
      hair_color: "Dark Blue",
      power_type: "Chakra",
      weapon_type: "Byakugan",
      role: "Supporting",
    },
    {
      character_name: "Gaara",
      anime_name: "Naruto",
      hair_color: "Red",
      power_type: "Chakra",
      weapon_type: "Sand",
      role: "Supporting",
    },
    {
      character_name: "Rock Lee",
      anime_name: "Naruto",
      hair_color: "Black",
      power_type: "Taijutsu",
      weapon_type: "Fist",
      role: "Supporting",
    },
    {
      character_name: "Frieza",
      anime_name: "Dragon Ball Z",
      hair_color: "None",
      power_type: "Ki",
      weapon_type: "Energy Blasts",
      role: "Antagonist",
    },
    {
      character_name: "Cell",
      anime_name: "Dragon Ball Z",
      hair_color: "None",
      power_type: "Ki",
      weapon_type: "Energy Blasts",
      role: "Antagonist",
    },
    {
      character_name: "Gohan",
      anime_name: "Dragon Ball Z",
      hair_color: "Black",
      power_type: "Ki",
      weapon_type: "Energy Blasts",
      role: "Supporting",
    },
    {
      character_name: "Piccolo",
      anime_name: "Dragon Ball Z",
      hair_color: "None",
      power_type: "Ki",
      weapon_type: "Energy Blasts",
      role: "Supporting",
    },
    {
      character_name: "Trunks",
      anime_name: "Dragon Ball Z",
      hair_color: "Purple",
      power_type: "Ki",
      weapon_type: "Sword",
      role: "Supporting",
    },
    {
      character_name: "Marco",
      anime_name: "One Piece",
      hair_color: "Blonde",
      power_type: "Devil Fruit",
      weapon_type: "Phoenix Powers",
      role: "Supporting",
    },
    {
      character_name: "Ace",
      anime_name: "One Piece",
      hair_color: "Black",
      power_type: "Devil Fruit",
      weapon_type: "Fire",
      role: "Supporting",
    },
    {
      character_name: "Shanks",
      anime_name: "One Piece",
      hair_color: "Red",
      power_type: "Haki",
      weapon_type: "Sword",
      role: "Supporting",
    },
    {
      character_name: "Nami",
      anime_name: "One Piece",
      hair_color: "Orange",
      power_type: "Weather Control",
      weapon_type: "Clima-Tact",
      role: "Supporting",
    },
    {
      character_name: "Sanji",
      anime_name: "One Piece",
      hair_color: "Blonde",
      power_type: "Fighting Skills",
      weapon_type: "Legs",
      role: "Supporting",
    },
    {
      character_name: "L",
      anime_name: "Death Note",
      hair_color: "Black",
      power_type: "Intelligence",
      weapon_type: "Deductive Skills",
      role: "Antagonist",
    },
    {
      character_name: "Near",
      anime_name: "Death Note",
      hair_color: "White",
      power_type: "Intelligence",
      weapon_type: "Deductive Skills",
      role: "Supporting",
    },
    {
      character_name: "Misa Amane",
      anime_name: "Death Note",
      hair_color: "Blonde",
      power_type: "Shinigami Eyes",
      weapon_type: "Death Note",
      role: "Supporting",
    },
    {
      character_name: "Yuno Gasai",
      anime_name: "Future Diary",
      hair_color: "Pink",
      power_type: "Future Diary",
      weapon_type: "Various",
      role: "Supporting",
    },
    {
      character_name: "Yukiteru Amano",
      anime_name: "Future Diary",
      hair_color: "Black",
      power_type: "Future Diary",
      weapon_type: "Various",
      role: "Protagonist",
    },
    {
      character_name: "Ken Kaneki",
      anime_name: "Tokyo Ghoul",
      hair_color: "Black",
      power_type: "Ghoul Abilities",
      weapon_type: "Kagune",
      role: "Protagonist",
    },
    {
      character_name: "Rize Kamishiro",
      anime_name: "Tokyo Ghoul",
      hair_color: "Purple",
      power_type: "Ghoul Abilities",
      weapon_type: "Kagune",
      role: "Antagonist",
    },
    {
      character_name: "Arima Kishou",
      anime_name: "Tokyo Ghoul",
      hair_color: "White",
      power_type: "Combat Skills",
      weapon_type: "Quinque",
      role: "Antagonist",
    },
    {
      character_name: "Juuzou Suzuya",
      anime_name: "Tokyo Ghoul",
      hair_color: "White",
      power_type: "Combat Skills",
      weapon_type: "Quinque",
      role: "Supporting",
    },
    {
      character_name: "Kuroko Tetsuya",
      anime_name: "Kuroko no Basket",
      hair_color: "Light Blue",
      power_type: "Misdirection",
      weapon_type: "Basketball",
      role: "Protagonist",
    },
    {
      character_name: "Aomine Daiki",
      anime_name: "Kuroko no Basket",
      hair_color: "Dark Blue",
      power_type: "Zone",
      weapon_type: "Basketball",
      role: "Antagonist",
    },
    {
      character_name: "Kagami Taiga",
      anime_name: "Kuroko no Basket",
      hair_color: "Red",
      power_type: "Zone",
      weapon_type: "Basketball",
      role: "Protagonist",
    },
    {
      character_name: "Akashi Seijuro",
      anime_name: "Kuroko no Basket",
      hair_color: "Red",
      power_type: "Emperor Eye",
      weapon_type: "Basketball",
      role: "Antagonist",
    },
    {
      character_name: "Kise Ryota",
      anime_name: "Kuroko no Basket",
      hair_color: "Blonde",
      power_type: "Perfect Copy",
      weapon_type: "Basketball",
      role: "Supporting",
    },
    {
      character_name: "Midorima Shintaro",
      anime_name: "Kuroko no Basket",
      hair_color: "Green",
      power_type: "High Project Three",
      weapon_type: "Basketball",
      role: "Supporting",
    },
    {
      character_name: "Murasakibara Atsushi",
      anime_name: "Kuroko no Basket",
      hair_color: "Purple",
      power_type: "Zone",
      weapon_type: "Basketball",
      role: "Supporting",
    },
    {
      character_name: "Shoyo Hinata",
      anime_name: "Haikyuu!!",
      hair_color: "Orange",
      power_type: "Jumping Power",
      weapon_type: "Volleyball",
      role: "Protagonist",
    },
    {
      character_name: "Tobio Kageyama",
      anime_name: "Haikyuu!!",
      hair_color: "Black",
      power_type: "Precision Setting",
      weapon_type: "Volleyball",
      role: "Supporting",
    },
    {
      character_name: "Koshi Sugawara",
      anime_name: "Haikyuu!!",
      hair_color: "Grey",
      power_type: "Game Sense",
      weapon_type: "Volleyball",
      role: "Supporting",
    },
    {
      character_name: "Asuka Langley Soryu",
      anime_name: "Neon Genesis Evangelion",
      hair_color: "Red",
      power_type: "EVA Pilot",
      weapon_type: "EVA Unit 02",
      role: "Supporting",
    },
    {
      character_name: "Rei Ayanami",
      anime_name: "Neon Genesis Evangelion",
      hair_color: "Blue",
      power_type: "EVA Pilot",
      weapon_type: "EVA Unit 00",
      role: "Supporting",
    },
    {
      character_name: "Shinji Ikari",
      anime_name: "Neon Genesis Evangelion",
      hair_color: "Brown",
      power_type: "EVA Pilot",
      weapon_type: "EVA Unit 01",
      role: "Protagonist",
    },
    {
      character_name: "Ymir",
      anime_name: "Attack on Titan",
      hair_color: "Black",
      power_type: "Titan Shifter",
      weapon_type: "Jaw Titan",
      role: "Supporting",
    },
    {
      character_name: "Pieck Finger",
      anime_name: "Attack on Titan",
      hair_color: "Black",
      power_type: "Titan Shifter",
      weapon_type: "Cart Titan",
      role: "Supporting",
    },
    {
      character_name: "Gabi Braun",
      anime_name: "Attack on Titan",
      hair_color: "Black",
      power_type: "Marksmanship",
      weapon_type: "Rifle",
      role: "Supporting",
    },
    {
      character_name: "Falco Grice",
      anime_name: "Attack on Titan",
      hair_color: "Blonde",
      power_type: "Titan Shifter",
      weapon_type: "Jaw Titan",
      role: "Supporting",
    },
    {
      character_name: "Shigaraki Nana",
      anime_name: "My Hero Academia",
      hair_color: "Black",
      power_type: "Quirk (Float)",
      weapon_type: "Combat Skills",
      role: "Supporting",
    },
    {
      character_name: "Mirio Togata",
      anime_name: "My Hero Academia",
      hair_color: "Blonde",
      power_type: "Quirk (Permeation)",
      weapon_type: "Combat Skills",
      role: "Supporting",
    },
    {
      character_name: "Tamaki Amajiki",
      anime_name: "My Hero Academia",
      hair_color: "Dark Blue",
      power_type: "Quirk (Manifest)",
      weapon_type: "Food",
      role: "Supporting",
    },
    {
      character_name: "Lucy",
      anime_name: "Cyberpunk: Edgerunners",
      hair_color: "Pink",
      power_type: "Cybernetic Enhancement",
      weapon_type: "Various",
      role: "Supporting",
    },
    {
      character_name: "David Martinez",
      anime_name: "Cyberpunk: Edgerunners",
      hair_color: "Brown",
      power_type: "Cybernetic Enhancement",
      weapon_type: "Various",
      role: "Protagonist",
    },
    {
      character_name: "Rebecca",
      anime_name: "Cyberpunk: Edgerunners",
      hair_color: "Pink",
      power_type: "Cybernetic Enhancement",
      weapon_type: "Guns",
      role: "Supporting",
    },
    {
      character_name: "Maine",
      anime_name: "Cyberpunk: Edgerunners",
      hair_color: "None",
      power_type: "Cybernetic Enhancement",
      weapon_type: "Cybernetic Arms",
      role: "Supporting",
    },
    {
      character_name: "Yuta Okkotsu",
      anime_name: "Jujutsu Kaisen",
      hair_color: "Black",
      power_type: "Cursed Technique",
      weapon_type: "Cursed Energy",
      role: "Supporting",
    },
    {
      character_name: "Mei Mei",
      anime_name: "Jujutsu Kaisen",
      hair_color: "Black",
      power_type: "Cursed Technique",
      weapon_type: "Bird Control",
      role: "Supporting",
    },
    {
      character_name: "Suguru Geto",
      anime_name: "Jujutsu Kaisen",
      hair_color: "Black",
      power_type: "Cursed Technique",
      weapon_type: "Cursed Spirits",
      role: "Antagonist",
    },
    {
      character_name: "Toge Inumaki",
      anime_name: "Jujutsu Kaisen",
      hair_color: "Grey",
      power_type: "Cursed Speech",
      weapon_type: "Voice",
      role: "Supporting",
    },
    {
      character_name: "Tengen Uzui",
      anime_name: "Demon Slayer",
      hair_color: "White",
      power_type: "Breathing Techniques",
      weapon_type: "Dual Nichirin Swords",
      role: "Supporting",
    },
    {
      character_name: "Muichiro Tokito",
      anime_name: "Demon Slayer",
      hair_color: "Green",
      power_type: "Breathing Techniques",
      weapon_type: "Nichirin Sword",
      role: "Supporting",
    },
    {
      character_name: "Mitsuri Kanroji",
      anime_name: "Demon Slayer",
      hair_color: "Pink",
      power_type: "Breathing Techniques",
      weapon_type: "Nichirin Sword",
      role: "Supporting",
    },
    {
      character_name: "Obanai Iguro",
      anime_name: "Demon Slayer",
      hair_color: "Black",
      power_type: "Breathing Techniques",
      weapon_type: "Nichirin Sword",
      role: "Supporting",
    },
    {
      character_name: "Gyomei Himejima",
      anime_name: "Demon Slayer",
      hair_color: "Black",
      power_type: "Breathing Techniques",
      weapon_type: "Nichirin Axe and Ball",
      role: "Supporting",
    },
    {
      character_name: "Sanemi Shinazugawa",
      anime_name: "Demon Slayer",
      hair_color: "White",
      power_type: "Breathing Techniques",
      weapon_type: "Nichirin Sword",
      role: "Supporting",
    },
    {
      character_name: "Akaza",
      anime_name: "Demon Slayer",
      hair_color: "Pink",
      power_type: "Demon Powers",
      weapon_type: "Blood Demon Art",
      role: "Antagonist",
    },
    {
      character_name: "Kokushibo",
      anime_name: "Demon Slayer",
      hair_color: "Black",
      power_type: "Demon Powers",
      weapon_type: "Blood Demon Art",
      role: "Antagonist",
    },
    {
      character_name: "Daki",
      anime_name: "Demon Slayer",
      hair_color: "White",
      power_type: "Demon Powers",
      weapon_type: "Blood Demon Art",
      role: "Antagonist",
    },
    {
      character_name: "Gyutaro",
      anime_name: "Demon Slayer",
      hair_color: "Black",
      power_type: "Demon Powers",
      weapon_type: "Blood Demon Art",
      role: "Antagonist",
    },
    {
      character_name: "Kaori Miyazono",
      anime_name: "Your Lie in April",
      hair_color: "Blonde",
      power_type: "Musical Talent",
      weapon_type: "Violin",
      role: "Supporting",
    },
    {
      character_name: "Kousei Arima",
      anime_name: "Your Lie in April",
      hair_color: "Black",
      power_type: "Musical Talent",
      weapon_type: "Piano",
      role: "Protagonist",
    },
    {
      character_name: "Shirase Kobuchizawa",
      anime_name: "A Place Further Than The Universe",
      hair_color: "Black",
      power_type: "Determination",
      weapon_type: "None",
      role: "Protagonist",
    },
    {
      character_name: "Mari Tamaki",
      anime_name: "A Place Further Than The Universe",
      hair_color: "Brown",
      power_type: "None",
      weapon_type: "None",
      role: "Supporting",
    },
    {
      character_name: "Shouko Nishimiya",
      anime_name: "A Silent Voice",
      hair_color: "Brown",
      power_type: "None",
      weapon_type: "None",
      role: "Protagonist",
    },
    {
      character_name: "Shouya Ishida",
      anime_name: "A Silent Voice",
      hair_color: "Black",
      power_type: "None",
      weapon_type: "None",
      role: "Protagonist",
    },
    {
      character_name: "Mitsuha Miyamizu",
      anime_name: "Your Name",
      hair_color: "Black",
      power_type: "Body Switching",
      weapon_type: "None",
      role: "Protagonist",
    },
    {
      character_name: "Taki Tachibana",
      anime_name: "Your Name",
      hair_color: "Black",
      power_type: "Body Switching",
      weapon_type: "None",
      role: "Protagonist",
    },
    {
      character_name: "Hina Amano",
      anime_name: "Weathering with You",
      hair_color: "Black",
      power_type: "Weather Manipulation",
      weapon_type: "None",
      role: "Protagonist",
    },
    {
      character_name: "Hodaka Morishima",
      anime_name: "Weathering with You",
      hair_color: "Black",
      power_type: "None",
      weapon_type: "None",
      role: "Protagonist",
    },
    {
      character_name: "Riko",
      anime_name: "Made in Abyss",
      hair_color: "Blonde",
      power_type: "None",
      weapon_type: "Various Tools",
      role: "Protagonist",
    },
    {
      character_name: "Reg",
      anime_name: "Made in Abyss",
      hair_color: "Black",
      power_type: "Robot Powers",
      weapon_type: "Incinerator",
      role: "Supporting",
    },
    {
      character_name: "Nanachi",
      anime_name: "Made in Abyss",
      hair_color: "White",
      power_type: "Enhanced Senses",
      weapon_type: "Knowledge",
      role: "Supporting",
    },
    {
      character_name: "Bondrewd",
      anime_name: "Made in Abyss",
      hair_color: "None",
      power_type: "Artifacts",
      weapon_type: "Various",
      role: "Antagonist",
    },
    {
      character_name: "Phosphophyllite",
      anime_name: "Land of the Lustrous",
      hair_color: "Green",
      power_type: "Gem Body",
      weapon_type: "None",
      role: "Protagonist",
    },
    {
      character_name: "Diamond",
      anime_name: "Land of the Lustrous",
      hair_color: "White",
      power_type: "Gem Body",
      weapon_type: "Sword",
      role: "Supporting",
    },
    {
      character_name: "Bort",
      anime_name: "Land of the Lustrous",
      hair_color: "Black",
      power_type: "Gem Body",
      weapon_type: "Sword",
      role: "Supporting",
    },
    {
      character_name: "Cinnabar",
      anime_name: "Land of the Lustrous",
      hair_color: "Red",
      power_type: "Gem Body",
      weapon_type: "Mercury",
      role: "Supporting",
    },
    {
      character_name: "Takemichi Hanagaki",
      anime_name: "Tokyo Revengers",
      hair_color: "Black",
      power_type: "Time Leaping",
      weapon_type: "Fist",
      role: "Protagonist",
    },
    {
      character_name: "Mikey",
      anime_name: "Tokyo Revengers",
      hair_color: "Blonde",
      power_type: "Combat Skills",
      weapon_type: "Kicks",
      role: "Supporting",
    },
    {
      character_name: "Draken",
      anime_name: "Tokyo Revengers",
      hair_color: "Blonde",
      power_type: "Combat Skills",
      weapon_type: "Fist",
      role: "Supporting",
    },
    {
      character_name: "Chifuyu Matsuno",
      anime_name: "Tokyo Revengers",
      hair_color: "Black",
      power_type: "Combat Skills",
      weapon_type: "Fist",
      role: "Supporting",
    },
    {
      character_name: "Kazutora Hanemiya",
      anime_name: "Tokyo Revengers",
      hair_color: "Yellow and Black",
      power_type: "Combat Skills",
      weapon_type: "Various",
      role: "Antagonist",
    },
  ],
};
